train: [] # metrics that are calculated during training
inference: # metrics that are calculated during inference (eval)
  - _target_: src.metrics.ArgmaxCERMetric
    name: "CER_(Argmax)" # it is better to avoid spaces in names
  - _target_: src.metrics.ArgmaxWERMetric
    name: "WER_(Argmax)"
  - _target_: src.metrics.BeamSearchCERMetric
    beam_size: 10
    name: "CER_(BeamSearch)" # it is better to avoid spaces in names
  - _target_: src.metrics.BeamSearchWERMetric
    name: "WER_(BeamSearch)"
    beam_size: 10
